# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extract_psi_cpp <- function(x, node_preds, tree_paths, node_ids, split_vars, split_vals) {
    .Call(`_nerfplus_extract_psi_cpp`, x, node_preds, tree_paths, node_ids, split_vars, split_vals)
}

extract_psi_chr_cpp <- function(x, node_preds, tree_paths, node_ids, split_vars, split_vals, unordered_factors) {
    .Call(`_nerfplus_extract_psi_chr_cpp`, x, node_preds, tree_paths, node_ids, split_vars, split_vals, unordered_factors)
}

rnc_solver <- function(X, Y, L, H, W, lambda_netcoh) {
    .Call(`_nerfplus_rnc_solver`, X, Y, L, H, W, lambda_netcoh)
}

rnc_solver_naive <- function(X, Y, L, H, W, lambda_netcoh) {
    .Call(`_nerfplus_rnc_solver_naive`, X, Y, L, H, W, lambda_netcoh)
}

rnc_nodeids_solver <- function(X, Y, L, H, W, X_alpha, lambda_netcoh) {
    .Call(`_nerfplus_rnc_nodeids_solver`, X, Y, L, H, W, X_alpha, lambda_netcoh)
}

rnc_nodeids_solver_naive <- function(X, Y, L, H, W, X_alpha, lambda_netcoh) {
    .Call(`_nerfplus_rnc_nodeids_solver_naive`, X, Y, L, H, W, X_alpha, lambda_netcoh)
}

rnc_solver_path <- function(X, Y, L, lambda_netcoh, lambdas_x) {
    .Call(`_nerfplus_rnc_solver_path`, X, Y, L, lambda_netcoh, lambdas_x)
}

rnc_solver_path_predict <- function(X, Y, L, X_test, Y_test, L22, L21, lambda_netcoh, lambdas_x, return_fit) {
    .Call(`_nerfplus_rnc_solver_path_predict`, X, Y, L, X_test, Y_test, L22, L21, lambda_netcoh, lambdas_x, return_fit)
}

rnc_nodeids_solver_path <- function(X, Y, L, lambda_netcoh, lambdas_x, X_alpha) {
    .Call(`_nerfplus_rnc_nodeids_solver_path`, X, Y, L, lambda_netcoh, lambdas_x, X_alpha)
}

rnc_logistic_solver <- function(X, Y, L, H, lambda_netcoh, theta_init, maxit, tol, verbose) {
    .Call(`_nerfplus_rnc_logistic_solver`, X, Y, L, H, lambda_netcoh, theta_init, maxit, tol, verbose)
}

get_tree_paths_cpp <- function(terminal_node_ids, left_child_ids, right_child_ids, node_ids) {
    .Call(`_nerfplus_get_tree_paths_cpp`, terminal_node_ids, left_child_ids, right_child_ids, node_ids)
}

